Remove dynamic exception specification to fix C++17 compatibility
The dynamic exception specifications have been deprecated in C++11
and eventually removed in C++17 [1].  GCC-11 uses gnu++17 by default,
causing advancecomp to fail to compile:

    In file included from rezip.cc:24:
    file.h:70:43: error: ISO C++17 does not allow dynamic exception specifications
       70 | bool file_exists(const std::string& file) throw (error);
          |                                           ^~~~~
    file.h:71:75: error: ISO C++17 does not allow dynamic exception specifications
       71 | e(const std::string& path, const char* data, unsigned size) throw (error);
          |                                                             ^~~~~
    ...

Since there is really no gain from having these specifications anymore,
just remove them to fix the build.

[1] https://en.cppreference.com/w/cpp/language/except_spec